<?php

namespace bbs;


class DeBolleHarten extends SystemCard
{
	public function listOpeningBids()
	{
		return [
			'PASS' => [
				'VERYWEAK, WEAK, INVITATIONAL'
			],
			'1C' => [
				'=4=4=4=1, OPENING, STRONG, VERYSTRONG, FOUR441',
				'=4=4=1=4, OPENING, STRONG, VERYSTRONG, FOUR441',
				'-3+4+0+0, OPENING, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED, FORCING',
				'=4+5+0+0, OPENING, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED, FORCING',
				'=5+6+0+0, OPENING, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED, FORCING',
			],
			'1D' => [
				'+4-3+0+0, OPENING, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED, FORCING',
				'+5-5+0+0, OPENING, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED, FORCING'
			],
			'1H' => [
				'BALANCED, SEMIBALANCED, WEAKNOTRUMP',
				'BALANCED, SEMIBALANCED, STRONGERNOTRUMP, FORCING',
			],
			'1S' => [
				'=1=4=4=4, OPENING, STRONG, VERYSTRONG, FOUR441',
				'=4=1=4=4, OPENING, STRONG, VERYSTRONG, FOUR441',
				'-3-3+5+0, OPENING, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED, FORCING',
			],
			'1N' => [
				'BALANCED, SEMIBALANCED, STRONGNOTRUMP, NOTFORCING',
			],
			'2C' => [
				'-3-3-4+5, OPENING, UNBALANCED, SEMIBALANCED, NOTFORCING',
				'-3-3=5+6, OPENING, UNBALANCED, SEMIBALANCED, NOTFORCING',
			],
			'2D' => [
				'-3=6+0+0, PREEMPTIVE',
				'=6-3+0+0, PREEMPTIVE',
				'BALANCED, SEMIBALANCED, THREENOTRUMP, FOURNOTRUMP, FIVENOTRUMP, SIXNOTRUMP, SEVENNOTRUMP, FORCING',
			],
			'2H' => [
				'-3-3-4+5, STRONG, VERYSTRONG, UNBALANCED, SEMIBALANCED',
				'-2-2=5+6, STRONG, VERYSTRONG, UNBALANCED, FORCING',
			],
			'2S' => [
				'=5-3+0+4, PREEMPTIVE, UNBALANCED, SEMIBALANCED',
				'=5-3+4+0, PREEMPTIVE, TWOSUITED',
			],
			'2N' => [
				'BALANCED, SEMIBALANCED, TWONOTRUMP',
			],
			'3C' => [
				'-3-3+0+6, PREEMPTIVE',
			],
			'3D' => [
				'-3-3+6+0, PREEMPTIVE',
			],
			'3H' => [
				'-3+6+0+0, PREEMPTIVE',
			],
			'3S' => [
				'+6-3+0+0, PREEMPTIVE',
			],
		];
	}
}


